name: nf-ga4gh CI (test)
on:
  push:

jobs:
  test:
    name: NXF ${{ matrix.nextflow_version }} / Java ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        nextflow_version: [
            '25.10',
        ]
        java_version: [
            17,
            21,
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: 'gradle'

      # TODO: This is a bit of clunky code since we weren't able to get `NXF_PLUGINS_DEV` working as expected
      #       i.e. Was only able to use the local plugin by explicitly setting the version in the `Install nf-canary` step below
      #       Is there a better way to have Nextflow use the locally-built plugin?
      - name: Get plugin version
        shell: bash
        run: |
          PLUGIN_VERSION="$(awk -F': ' '$1=="Plugin-Version"{print $2}' plugins/nf-ga4gh/src/resources/META-INF/MANIFEST.MF | tr -d '\r')"
          echo "PLUGIN_VERSION=${PLUGIN_VERSION}" >> "$GITHUB_ENV"
          echo "Using plugin version: ${PLUGIN_VERSION}"
                  
      - name: Build Plugin
        run: |
          make buildPlugins
          mkdir -p ~/.nextflow/plugins/
          cp -r build/plugins/nf-ga4gh-$PLUGIN_VERSION ~/.nextflow/plugins/

      - name: Install Nextflow ${{ matrix.nextflow_version }}
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.nextflow_version }}

      # TODO: Could try adding other TES implementations here like TESK, Sprocket, Poiesis, etc...
      #       - https://github.com/elixir-cloud-aai/TESK
      #       - https://github.com/stjude-rust-labs/sprocket
      #       - https://github.com/JaeAeich/poiesis
      - name: Install TES Server
        run: |
          # https://github.com/ohsu-comp-bio/funnel/releases/tag/v0.11.8
          curl -fsSL https://ohsu-comp-bio.github.io/funnel/install.sh | bash -s -- v0.11.8

      - name: Start TES Server
        run: |
          funnel server run > funnel.log 2>&1 &

      - name: Install nf-canary
        run: |
          cd ..
          git clone https://github.com/seqeralabs/nf-canary
          cd nf-canary
          cat <<EOF > nextflow.config.tes
          plugins {
            id "nf-ga4gh@$PLUGIN_VERSION"   // <---- Explictly setting the plugin version here...
          }
          // Nextflow config file for running on TES Backend
          process {
              executor = 'tes'
              container = 'ubuntu:latest'
          }
          params {
              // TES
              endpoint                   = 'http://localhost:8000'
              basicUsername              = null
              basicPassword              = null
          }
          EOF

      - name: Run nf-canary
        run: |
          cd ../nf-canary
          export NXF_ANSI_LOG=false
          nextflow run main.nf -c nextflow.config.tes \
            -with-report report.html \
            -with-timeline timeline.html

      - name: Stage Reports
        if: always()
        run: |
          mkdir -p $GITHUB_WORKSPACE/results
          cd ../nf-canary
          
          # Nextflow Logs
          cp -f report.html timeline.html .nextflow.log $GITHUB_WORKSPACE/results/ || true

          # Funnel Logs
          cp -f $GITHUB_WORKSPACE/funnel.log $GITHUB_WORKSPACE/results/ || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nf-canary-results-nxf-${{ matrix.nextflow_version }}-java${{ matrix.java_version }}
          path: results/
          retention-days: 7
