name: nf-ga4gh CI (test)
on:
  push:

jobs:
  test:
    name: NXF ${{ matrix.nextflow_version }} / Java ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        # TODO: Possible way to automatically fetch latest nextflow versions to prevent drift?
        #       e.g. from nf-core/setup-nextflow action → https://github.com/nf-core/setup-nextflow
        #       Or better to manually add/remove as needed?
        nextflow_version: [
            '25.10.0', 
            '25.10.4', 
            '25.10',
        ]
        # TODO: Same question for Java versions:
        #       e.g. from setup/java action → https://github.com/actions/setup-java
        #       Probably better to simply manually manage versions for now...
        java_version: [
            17,
            21
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build and Test
        run: |
          make clean
          make assemble
          make test
        env:
          NXF_VER: ${{ matrix.nextflow_version }}
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'
